### ISSUE TITLE
Changes needed on the landing page

### ISSUE THREAD

**Issue by ClaytonSiby** [yigitm/Online-Directory#2]
Great work on the project, the site looks amazing, however, there are some things that you need to fix on the landing page. I will list down all the issues raised.

* Try and replace nav list items with icons when you come to small sizes.
* add more margin on the search bar so that it doesn't touch the left edge of the screen.
* increase font-size on the logo for small screen sizes & also center it.
* remove margin in the game section and use padding-top & bottom instead, when it comes to small devices.

**Comment by yigitm** [comment]
- [x]  Try and replace nav list items with icons when you come to small sizes.
- [x]  add more margin on the search bar so that it doesn't touch the left edge of the screen.
- [x]  increase font-size on the logo for small screen sizes & also center it.
- [x]  remove margin in the game section and use padding-top & bottom instead, when it comes to small devices.
